In [1]:
import numpy as np

In [2]:
m = np.array(3)
m

array(3)

In [4]:
m.ndim  # dimensional

0

In [7]:
m.shape  # shape of an array

()

In [6]:
m.dtype  # data type

dtype('int64')

In [9]:
a = np.array(1, 2)
a

TypeError: Cannot interpret '2' as a data type

In [10]:
a = np.array([1, 2])
a

array([1, 2])

In [11]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [12]:
b = np.array([1, 2, 3, 4, 5])
b

array([1, 2, 3, 4, 5])

In [13]:
a.ndim

1

In [14]:
b.ndim

1

In [15]:
a.shape

(5,)

In [16]:
b.shape

(5,)

In [17]:
a.dtype

dtype('int64')

In [18]:
a

array([1, 2, 3, 4, 5])

In [20]:
b

array([1, 2, 3, 4, 5])

In [21]:
a + b

array([ 2,  4,  6,  8, 10])

In [22]:
a * b

array([ 1,  4,  9, 16, 25])

In [24]:
a / b

array([1., 1., 1., 1., 1.])

In [25]:
v = np.array([[1, 2, 3], [4, 5, 6]])
v

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
v.ndim

2

In [27]:
v.shape

(2, 3)

In [28]:
s = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
s.ndim

2

In [30]:
s.shape

(3, 3)

In [31]:
s.dtype

dtype('int64')

In [35]:
l = np.zeros(5)
l

array([0., 0., 0., 0., 0.])

In [36]:
l.shape

(5,)

In [37]:
l.ndim

1

In [38]:
l.dtype

dtype('float64')

In [43]:
k = np.zeros([5, 5])
k

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
k.ndim

2

In [42]:
k.shape

(5, 5)

In [45]:
o = np.zeros(5, int)
o

array([0, 0, 0, 0, 0])

In [46]:
o.dtype

dtype('int64')

In [47]:
o.ndim

1

In [48]:
o.shape

(5,)

In [50]:
np.zeros(5, float)

array([0., 0., 0., 0., 0.])

In [52]:
c = np.zeros([5, 5], complex)
c

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [53]:
c.dtype

dtype('complex128')

In [54]:
c.ndim

2

In [58]:
p = np.zeros([5, 2, 3], int)   # 5 set with 2 rows and 3 columns
p

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [56]:
p.ndim

3

In [57]:
p.shape

(5, 2, 3)

In [59]:
p.dtype

dtype('int64')

In [60]:
d = np.ones(7, int)
d

array([1, 1, 1, 1, 1, 1, 1])

In [62]:
d.dtype

dtype('int64')

In [64]:
e = np.ones(7, float)
e

array([1., 1., 1., 1., 1., 1., 1.])

In [65]:
e.dtype

dtype('float64')

In [67]:
f = np.zeros(shape = (3, 5, 2))
f

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [68]:
f.ndim

3

In [69]:
f.dtype

dtype('float64')

In [70]:
f.shape

(3, 5, 2)

In [75]:
g = np.zeros(shape = [2, 3, 4], dtype = int)
g

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [76]:
g.dtype

dtype('int64')

In [77]:
g.ndim

3

In [78]:
g.shape

(2, 3, 4)

In [84]:
z = np.array([1, 2, 3], ndmin = 2)
z

array([[1, 2, 3]])

In [85]:
z.ndim

2