In [2]:
# Defining arrays of various dimensions

import numpy as np

In [3]:
array_0d = np.array(7)
array_1d = np.array([1, 2, 3])
array_2d = np.array([[1, 2], [3, 4], [5, 6]])
array_3d = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])

In [4]:
array_0d

array(7)

In [5]:
array_1d

array([1, 2, 3])

In [8]:
array_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
array_3d

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [11]:
# Operating on 0d array
array_0d.ndim # number of dimensional

0

In [12]:
array_0d.shape  # shape of an array

()

In [14]:
array_0d.size  # number of elements in the array

1

In [16]:
array_0d.dtype   # Data types of elements in the array

dtype('int64')

In [17]:
array_0d.itemsize  # size of each element in bytes

8

In [18]:
array_0d.nbytes  # total size of the array in bytes

8

In [19]:
array_0d.T  # Transpose of the array (not meaningful for 0d array)

array(7)

In [20]:
list(array_0d.flat)  # Flat iterator over the array

[7]

In [29]:
# Operating on 1d array
array_1d.ndim # number of dimensional

1

In [22]:
array_1d.shape  # shape of an array

(3,)

In [23]:
array_1d.size  # number of elements in the array

3

In [24]:
array_1d.dtype   # Data types of elements in the array

dtype('int64')

In [25]:
array_1d.itemsize  # size of each element in bytes

8

In [26]:
array_1d.nbytes  # total size of the array in bytes

24

In [27]:
array_1d.T  # Transpose of the array (not meaningful for 0d array)

array([1, 2, 3])

In [28]:
list(array_1d.flat)  # Flat iterator over the array

[1, 2, 3]

In [30]:
# Operating on 1d array
array_2d.ndim # number of dimensional

2

In [31]:
array_2d.shape  # shape of an array

(3, 2)

In [32]:
array_2d.size  # number of elements in the array

6

In [33]:
array_2d.dtype   # Data types of elements in the array

dtype('int64')

In [34]:
array_2d.itemsize  # size of each element in bytes

8

In [35]:
array_2d.nbytes  # total size of the array in bytes

48

In [36]:
array_2d.T  # Transpose of the array (not meaningful for 0d array)

array([[1, 3, 5],
       [2, 4, 6]])

In [37]:
list(array_2d.flat)  # Flat iterator over the array

[1, 2, 3, 4, 5, 6]