In [1]:
import numpy as np

In [13]:
array_from_list = np.array([1, 2, 3, 4, 5])
array_from_tuple = np.array((1, 2, 3, 4, 5))

In [14]:
array_from_list

array([1, 2, 3, 4, 5])

In [15]:
array_from_tuple

array([1, 2, 3, 4, 5])

In [17]:
zeros_array = np.zeros((3, 4)) # 3 x 4 array of zeros
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros(3, dtype = int)

array([0, 0, 0])

In [20]:
np.zeros((3, 4, 2), dtype = int)  # 3 set 4 rows 2 column

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [21]:
ones_array = np.ones((2, 3)) # 2 x 3 arrays of ones
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.ones((4, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [2]:
# np.full(shape, value) # Create an array filled with a specified value

In [3]:
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [42]:
np.full(7, 10)

array([10, 10, 10, 10, 10, 10, 10])

In [43]:
np.full((5, 2), 2)

array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

In [4]:
# np.arange(start, stop, step)  # Return evenly spaced values within a given interval

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [35]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
# np.linspace(start, stop, num) # Create an array of evenly spaced values over an interval

In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [39]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [41]:
np.linspace(20, 10, num = 4)

array([20.        , 16.66666667, 13.33333333, 10.        ])

In [44]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
# np.eye(N)
# Np.identity(N)
# Return a 2-D array with ones on the diagonal and zeros elsewhere i.e. Identiy Matrix

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.eye(3, k = 1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [28]:
np.eye(3, k = 2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.eye(3, k = 3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.eye(3, k = -1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [31]:
np.eye(3, k = -2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [32]:
np.eye(3, k = -2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [24]:
# np.identity()
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.identity(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [11]:
# np.empty(shape) # Create an uninitialized array

In [45]:
np.empty((2,2))

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [48]:
np.empty((3, 3))

array([[4.83226207e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])