**Example 1: Reshape a 1D Array into a 2D Array**

In [3]:
import numpy as np

# Create a 1D array with a elements
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape it into a 2D array with 2 rows and 3 columns
reshaped_arr = arr.reshape((2, 3))

print("Original Array: ")
print(arr)
print("Reshaped Array (2x3)")
print(reshaped_arr)

Original Array: 
[1 2 3 4 5 6]
Reshaped Array (2x3)
[[1 2 3]
 [4 5 6]]


**Example 2: Reshape a 1D Array into 3D array**

In [7]:
# Create a 1D array with 12 elements
arr = np.arange(1, 13)

# Reshpaed it into a 3D array with 2 matrices, each of size 2x3
reshaped_arr = arr.reshape(2, 2, 3)

print("Original Array:")
print(arr)
print("Reshaped Array (2x3x3):")
print(reshaped_arr)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array (2x3x3):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**Example 3: Using -1 in reshape() to Automatically infer a Dimension**

In [8]:
# Create a 1D array with 8 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshape it into a 2D array with 4 rows, ad Let NumPy calculate the number of columns
reshaped_arr = arr.reshape((4, -1))   # -1 Lets Numpy calculate the dimension

print("Original Array:")
print(arr)
print("Reshaped Array (4x2):")
print(reshaped_arr)

Original Array:
[1 2 3 4 5 6 7 8]
Reshaped Array (4x2):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**Example 4: Flattening a Multidimensional Array**

In [10]:
# Create a 2D array
arr = np.array([[1, 2], [3, 4], [5, 6]])

# Reshaped it into a 1D array (flatten it)
flattened_arr = arr.reshape(-1)

print("Original 2D Arrray: ")
print(arr)
print("Flattened Array:")
print(flattened_arr)

Original 2D Arrray: 
[[1 2]
 [3 4]
 [5 6]]
Flattened Array:
[1 2 3 4 5 6]


**Example 5: Reshape with an Incompatible Shape (Error Handling)**

In [16]:
# Create a 1D array with 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])

# Attempt to reshape into an incompatible shape
try:
  reshaped_arr = arr.reshape((3, 3))
  print(reshaped_arr)
except ValueError as e:
  print(f"Error : {e}")

Error : cannot reshape array of size 6 into shape (3,3)
