In [13]:
import numpy as np

In [14]:
# Creting a 2D array
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
print(arr)

[1 2 3 4 5 6]


In [16]:
print(list(arr))

[1, 2, 3, 4, 5, 6]


# numpy.ravel(a, order = 'C)

In [17]:
# Create a 2D array
arr = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape it into a 1D array (flatten it)
flattened_arr = arr.reshape(-1)

print("Original 2D Array:")
print(arr)
print("\nFlattened Array:")
print(flattened_arr)

Original 2D Array:
[[1 2]
 [3 4]
 [5 6]]

Flattened Array:
[1 2 3 4 5 6]


# numpy.ravel(a, order = 'C)

In [18]:
import numpy as np

# Creating a 2D arrya
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr, '\n\n')

# Flatten the array using ravel()
flattened = np.ravel(arr)
print(flattened)

[[1 2 3]
 [4 5 6]] 


[1 2 3 4 5 6]


In [19]:
# Flatten the array column-wise using ravel()
flattened_f = np.ravel(arr, order = 'F')

print(flattened_f)

[1 4 2 5 3 6]


In [20]:
# Using 'A' and 'K' orders
flattened_a = np.ravel(arr, order = 'A')
flattened_k = np.ravel(arr, order = 'K')

print(flattened_a)
print(flattened_k)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [21]:
# Creating a transposed array
arr_transposed = arr.T
arr_transposed

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
# Flattening the transposed array -- C F A K
flattened_transposed = np.ravel(arr_transposed, order = 'C')
print(flattened_transposed)

[1 4 2 5 3 6]


In [25]:
flattened_transposed = np.ravel(arr_transposed, order = 'F')
print(flattened_transposed)

[1 2 3 4 5 6]


In [26]:
flattened_transposed = np.ravel(arr_transposed, order = 'A')
print(flattened_transposed)

[1 2 3 4 5 6]


In [27]:
flattened_transposed = np.ravel(arr_transposed, order = 'K')
print(flattened_transposed)

[1 2 3 4 5 6]


**numpy.ndarray.flat**

In [31]:
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr,"\n\n")
# Using ndarray.flat to iterate over the array elements
for element in arr.flat:
  print(element)

[[1 2 3]
 [4 5 6]] 


1
2
3
4
5
6


In [30]:
# Accessing the third element using flat (zero-based indexing)
third_element = arr.flat[2]
print(third_element)

3


In [32]:
# Modifying elements using flat
arr.flat[2] = 10
print(arr)

[[ 1  2 10]
 [ 4  5  6]]


In [34]:
# Using flat to multiply each element by 2
for i in range(arr.size):
  arr.flat[i] *= 2

print(arr)

[[ 4  8 40]
 [16 20 24]]


In [36]:
# Converting the flat iterator to a list
flat_list = list(arr.flat)
print(flat_list)

# Converting to a NumPy arra
flat_array = np.array(arr.flat)
print(flat_array)

[4, 8, 40, 16, 20, 24]
[ 4  8 40 16 20 24]


# numpy.ndarray.flatten(order = 'C')

In [37]:
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening the array using flatten()
flattened = arr.flatten()
print(flattened)

[1 2 3 4 5 6]


In [38]:
# Flattening the array column-wise using flatten()
flattened_f = arr.flatten(order = 'F')
print(flattened_f)

[1 4 2 5 3 6]


In [39]:
# Using 'A' and 'K' orders
flattened_a = arr.flatten(order = 'a')
flattened_k = arr.flatten(order = 'k')

print(flattened_a)
print(flattened_k)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [40]:
# Creating a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Flattening the 3D array
flattened_3d = arr_3d.flatten()
flattened_3d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
# Modifying the flattened array

flattened[2] = 10

print(flattened, "\n\n")
print(arr)

[ 1  2 10  4  5  6] 


[[1 2 3]
 [4 5 6]]
